Proyecto/Backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

Proyecto/app/urls.py
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    path('', views.PaginaInicio, name='PaginaInicio'),
    path('post_login/', views.post_login, name='post_login'),
    path('post_logout/', views.post_logout, name='post_logout'),
    

    path('ActualizarSemestre/', views.ActualizarSemestre, name='ActualizarSemestre'),
    path('post_ActualizarSemestre/', views.post_ActualizarSemestre, name='post_ActualizarSemestre'),

    path('laconvocatoria/<int:id>/', views.laconvocatoria, name='laconvocatoria'),
    path('cerrarlaconvocatoria/<int:id>/', views.cerrarlaconvocatoria, name='cerrarlaconvocatoria'),


    path('Coordinador/', views.Coordinador, name='Coordinador'),

    path('crearConvocatoria/', views.crearConvocatoria, name='crearConvocatoria'),
    path('post_crearConvocatoria/', views.post_crearConvocatoria, name='post_crearConvocatoria'),
    
    path('editarConvocatoria/<int:id>/', views.editarConvocatoria, name='editarConvocatoria'),
    path('post_editarConvocatoria/<int:id>/', views.post_editarConvocatoria, name='post_editarConvocatoria'),

    path('crearEmpresa/', views.crearEmpresa, name='crearEmpresa'),
    path('post_crearEmpresa/', views.post_crearEmpresa, name='post_crearEmpresa'),

    path('crearEstudiante/', views.crearEstudiante, name='crearEstudiante'),
    path('post_crearEstudiante/', views.post_crearEstudiante, name='post_crearEstudiante'),

    path('Empresa/', views.lEmpresa, name='Empresa'),
    path('Error/', views.Error, name='Error'),
    path('Estudiante/', views.lEstudiante, name='Estudiante'),
    path('listaConvocatoriasespecificas/', views.listaConvocatoriasespecificas, name='listaConvocatoriasespecificas'),
    path('listaConvocatoriasEstudiantes/', views.listaConvocatoriasEstudiantes, name='listaConvocatoriasEstudiantes'),
    path('listaConvocatorias/', views.listaConvocatorias, name='listaConvocatorias'),
    path('listaEmpresas/', views.listaEmpresas, name='listaEmpresas'),
    path('listaPostulaciones/', views.listaPostulaciones, name='listaPostulaciones'),

    
    path('listadoEstudiantes/', views.listadoEstudiantes, name='listadoEstudiantes'),

    path('listadoEstuadiantesenPracticas/', views.listadoEstuadiantesenPracticas, name='listadoEstuadiantesenPracticas'),
    path('perfilEmpresa/<int:id>/', views.perfilEmpresa, name='perfilEmpresa'),

    path('perfilEstudiante/<int:id>/', views.perfilEstudiante, name='perfilEstudiante'),
    
    path('postulacionespecifica/', views.postulacionespecifica, name='postulacionespecifica'),
]

Proyecto/app/templates/app/Actualizar-S.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/actualizar-s.css' %}">
    <title>Actualizar Semestre</title>
</head>
<body>
    <div class="Principal">
        <div class="contenedor">
            <div class="header">
                <a class="Usuario" href="{% url 'app:Coordinador' %}"><h1>Coordinador</h1></a>
                <a class="salir" href="{% url 'app:PaginaInicio' %}">Cerrar Sesión</a>
            </div>
            <div class="contenedorbarra1">
                <!-- contenedor barra -->
            </div>    
        </div>
        <div class="actualizar">
            <form action="{% url 'app:post_ActualizarSemestre' %}" method="POST">
                {% csrf_token %}
                 
                <h2>Actualizar Semestre</h2>
                <label for="">Semestre:</label>
                <input type="text" name="semester">
                <button class="guardar">Guardar</button>
                
                
            </form>            
        </div>        
        
    </div>
    
</body>
</html>

Proyecto/app/templates/app/Coordinador.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/Icoordinador.css' %}">
    <title>Coordinador</title>
</head>
<body>
    <div class="Principal">
        <div class="contenedor">
            <div class="header">
                <a class="Usuario" href=""><h1>Coordinador</h1></a>
                <a class="salir" href="{% url 'app:PaginaInicio' %}">Cerrar Sesión</a>
            </div>
            <div class="contenedorbarra1">
                <!-- contenedor barra -->
            </div>    
        </div>
        <div class="botones">
            <a href="{% url 'app:ActualizarSemestre' %}"><button class="ActualizarS">Actualizar Semestre de Postulaciones</button></a>
            <br>
            <a href="{% url 'app:listaEmpresas' %}"><button class="CE">Consultar Empresas</button></a>
            <br>
            <a href="{% url 'app:listaConvocatorias' %}"><button class="CC">Consultar Convocatorias</button></a> 
                            
        </div>
        <div class="restodebotones">
            <a href="{% url 'app:listadoEstudiantes' %}"><button class="CLE">Consultar lista de estudiantes</button></a>
            <br>
            <a href="{% url 'app:listadoEstuadiantesenPracticas' %}"><button class="CLEP">Consultar Listado de Estudiantes en Práctica</button></a>
            <br>
            <a href="{% url 'app:crearEstudiante' %}"><button class="crearE">Crear Estudiante</button></a>
        </div>
        
    </div>
    
</body>
</html>

Proyecto/app/templates/app/Empresa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/Iempresa.css' %}">
    <title>Empresa</title>
</head>
<body>
    
    <div class="contenedor">
        <div class="header">
            <!-- {% if nombre %}
            <a class="Usuario" href=""><h1>{{ request.user.first_name }}</h1></a>
            {% endif %} -->
            <span>{{ request.user.username }}</span>
            <a href="{% url 'app:post_logout' %}">Lareputa</a>
        </div>
        
        <div class="contenedorbarra1">
            <!-- contenedor barra -->
     
            <a href="{% url 'app:listaConvocatoriasespecificas' %}"><button class="mirar">Consultar Convocatorias</button></a>
           
            <a href="{% url 'app:crearConvocatoria' %}"><button class="crear">Crear Convocatoria</button></a>
        
    </div>
        
     
    
</body>
</html>

Proyecto/app/templates/app/Error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/error.css' %}">
    <title>Mensaje de Error</title>
</head>
<body>
    <br><br><br><br>
    <h1>ERROR DE AUTENTICACIÓN</h1>
    <br>
    <h4>Usted no tiene acceso a esta página, por favor autentíquese en el perfil correcto para acceder</h4>
</body>
</html>

Proyecto/app/templates/app/Lista-Convocatorias.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/lista-Convocatorias.css' %}">
    <title>Convocatorias</title>
</head>
<body>
    
    <div class="contenedor">
        <div class="header">
            <a class="Usuario" href="{% url 'app:Coordinador' %}"><h1>Coordinador</h1></a>
            <a href="{% url 'app:PaginaInicio' %}">Cerrar Sesión</a>
        </div>
        
        <div class="contenedorbarra1">
            <!-- contenedor barra -->
        </div>
        <div class="contenedorbarra2">
            <!-- contenedor barra -->
        </div>
        <div class="convocatorias">
            <h1>Convocatorias</h1>
            <table>
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Empresa</th>
                        <th>Fecha Inicio</th>
                        <th>Fecha Cierre</th>
                        <th>N° Postulaciones</th>
                        <th>Estado</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for cc in convocatorias %}
                        <tr>
                            <td>{{ cc.nombre }}</td>
                            <td><a href="{% url 'app:perfilEmpresa' %}">{{ cc.empresa.usuarios.username }}</a></td>
                            <td>{{ cc.fecha_inicial }}</td>
                            <td>{{ cc.fecha_final }}</td>
                            <td>0</td>
                            <td>{{ cc.abierta }}</td>
                            <td><a href="{% url 'app:laconvocatoria' cc.id %}"><img src="{% static 'app/icon/ojo-ver.jpg' %}" 
                                alt="AL"
                                width="30px">
                                </a>
                            </td>
                        </tr>
                   {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
        
    
</body>
</html>

Proyecto/app/templates/app/Lista-empresas.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/lista-empresas.css' %}">
    <title>Empresas</title>
</head>
<body>
    
    <div class="contenedor">
        <div class="header">
            <a class="Usuario" href="{% url 'app:Coordinador' %}"><h1>Coordinador</h1></a>
            <a href="{% url 'app:PaginaInicio' %}">Cerrar Sesión</a>
        </div>
        
        <div class="contenedorbarra1">
            <!-- contenedor barra -->
        </div>
        <div class="contenedorbarra2">
            <!-- contenedor barra -->
        </div>
        <div class="empresas">
            <br>
            <br>
            <h1>Empresas Vinculadas</h1>  
            <br><br><br>
            <table>
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Ciudad</th>
                        <th>Nombre de Contacto</th>
                        <th>Correo Electronico</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for em in empresas %}
                        <tr>
                            <td>{{ em.usuarios.username }}</td>
                            <td>{{ em.ciudad }}</td>
                            <td>{{ em.nombre_contacto }}</td>
                            <td>{{ em.usuarios.email }}</td>
                            <td>{{ em.id }}</td>
                            
                            <td>
                                <a href="{% url 'app:perfilEmpresa' em.id %}"><img src="{% static 'app/icon/ojo-ver.jpg' %}" 
                                    alt="AL"
                                    width="30px">
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                                       
                </tbody>
            </table>
        </div>
    </div>
        
    
</body>
</html>

Proyecto/app/templates/app/Listado-Pestudiantes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/listado-Pestudiantes.css' %}">
    <title>Estudiantes en Prácticas</title>
</head>
<body>
    
    <div class="contenedor">
        <div class="header">
            <a class="Usuario" href="Coordinador.html"><h1>Coordinador</h1></a>
            <a href="index-PaginaInicio.html">Cerrar Sesión</a>
        </div>
        
        <div class="contenedorbarra1">
            <!-- contenedor barra -->
        </div>
        <div class="contenedorbarra2">
            <!-- contenedor barra -->
        </div>
        <div class="estudiantes">
            <br>
            <br>
            <h1>Listado de</h1>  
            <h1>Estudiantes en Práctica:</h1>
            <br>
            <table>
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellidos</th>
                        <th>Correo Electrónico</th>
                        <th>en Empresa</th>
                        <th>Fecha Inicial</th>
                        <th>Fecha Final</th>
                        <th>Semestre Prácticas</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>####</td>
                        <td>### ####</td>
                        <td>####@######.com</td>
                        <td>Empresa ##</td>
                        <td>##/##/##</td>
                        <td>##/##/##</td>
                        <td>2020-2</td>
                        <td><a href="Perfil-estudiante.html"><img src="icon/ojo-ver.jpg" 
                            alt="AL"
                            width="30px">
                            </a>
                        </td>
                    </tr>
                   
                </tbody>
            </table>
        </div>
    </div>
        
    
</body>
</html>

Proyecto/app/templates/app/Listado-estudiantes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/listado-estudiantes.css' %}">
    <title>Estudiantes</title>
</head>
<body>
    
    <div class="contenedor">
        <div class="header">
            <a class="Usuario" href="{% url 'app:Coordinador' %}"><h1>Coordinador</h1></a>
            <a href="{% url 'app:PaginaInicio' %}">Cerrar Sesión</a>
        </div>
        
        <div class="contenedorbarra1">
            <!-- contenedor barra -->
        </div>
        <div class="contenedorbarra2">
            <!-- contenedor barra -->
        </div>
        <div class="estudiantes">
            <br>
            <br>
            <h1>Listado de</h1>  
            <h1>Estudiantes:</h1>
            <br>
            <table>
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellidos</th>
                        <th>Correo Electrónico</th>
                        <th>Postulaciones Aceptadas</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in estudiantes %}
                        <tr>
                            <td>{{ e.usuarios.first_name }}</td>
                            <td>{{ e.usuarios.last_name }}</td>
                            <td>{{ e.usuarios.email }}</td>
                            <td>{{ 0 }}</td>
                            <td>
                                <a href="{% url 'app:perfilEstudiante' e.id %}"><img src="{% static 'app/icon/ojo-ver.jpg' %}" 
                                    alt="AL"
                                    width="30px">
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                                       
                </tbody>
            </table>
        </div>
    </div>
        
    
</body>
</html>

Proyecto/app/templates/app/Perfil-empresa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/perfil-empresa.css' %}">
    <title>Empresa</title>
</head>
<body>
    
    <div class="contenedor">
        <div class="header">
            <a class="Usuario" href="Coordinador.html"><h1>Coordinador</h1></a>
            <a href="{% url 'app:PaginaInicio' %}">Cerrar Sesión</a>
        </div>
        <div class="Mostrar">
            {% if empresa %}
                <h1>{{ empresa.usuarios.username }}</h1>
                <div class="datos">
                    <h2>Fecha de creación:</h2>
                    <span>{{ empresa.fecha_creacion }}</span>
                    <h2>Ciudad:</h2>
                    <span>{{ empresa.ciudad }}</span>
                    <h2>Nombre de Contacto:</h2>
                    <span>{{ empresa.nombre_contacto }}</span>
                    <h2>Correo Electrónico:</h2>
                    <span>{{ empresa.usuarios.email }}</span>
                </div>
                <a href="{% url 'app:listaConvocatoriasespecificas' %}"><button >Lista de Convocatorias</button></a>
            {% endif %}
        </div>
        <div class="contenedorbarra1">
            <!-- contenedor barra -->
        </div>
        <div class="contenedorbarra2">
            <!-- contenedor barra -->
        </div>
    </div>
        
    
</body>
</html>

Proyecto/app/templates/app/Perfil-estudiante.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/perfil-estudiante.css' %}">
    <title>Estudiante</title>
</head>
<body>
    
    <div class="contenedor">
        <div class="header">
            <a class="Usuario" href=""><h1>Usuario</h1></a>
            <a href="{% url 'app:PaginaInicio' %}">Cerrar Sesión</a>
        </div>
        <div class="Mostrar">
            <div class="datos">
                <br>
                <br>
                <br>
                <br>
                {% if estudiante %}
                    <h1>Nombre</h1>
                    <span>{{estudiante.usuarios.first_name}}</span>
                    <h1>Apellido</h1>
                    <span>{{estudiante.usuarios.last_name}}</span>
                    <br>
                    <h2>Correo Electrónico:</h2>
                    <span>{{estudiante.usuarios.email}}</span>
                    <br>
                    <h2>Fortalezas:</h2>
                    <br><br><br>
                    <h2>Herramientas:</h2>
                {% endif %}
                <br><br><br><br><br>
                <label class="definir" for="">Definir estado:</label>
                <select name="OS">
                    <option selected ></option>
                    <option value="1">Aceptar</option> 
                    <option value="2">Rechazar</option> 
                </select>
            </div>
            <div class="cambios">
                <a href="Estudiante.html"><button >Aplicar Cambios</button></a>
            </div>
            {% if estudiante %}
                <div class="fortalezas"><span>{{estudiante.fortalezas}}</span></div>
                <div class="Herramientas"><span>{{estudiante.herramientas}}</span></div>    
            {% endif %}
        
        </div>
        
        
        <div class="contenedorbarra1">
            <!-- contenedor barra -->
        </div>
        <div class="contenedorbarra2">
            <!-- contenedor barra -->
        </div>
    </div>
        
    
</body>
</html>

Proyecto/app/templates/app/Postulacion-especifica.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/postulacion-especifica.css' %}">
    <title>Postulación</title>
</head>
<body>
    
    <div class="contenedor">
        <div class="header">
            <a class="Usuario" href="Estudiante.html"><h1>Nombre del Estudiante</h1></a>
            <a href="index-PaginaInicio.html">Cerrar Sesión</a>
        </div>
        <div class="contenedorbarra1">
            <!-- contenedor barra -->
        </div>
        <div class="contenedorbarra2">
            <!-- contenedor barra -->
        </div>
        <div class="post"> 
            <div class="contenido">
                <br>
                <h2>Empresa:</h2>
                <br>
                <h2>Nombre de la Convocatoria:</h2>
                <h2>Descripción:</h2>
                <br><br><br><br><br><br><br><br>
                <h2>Fecha Inicial:</h2>
                <h2>Fecha de Cierre:</h2>
                <h2>Fecha de Postulación</h2>
                <br>
                <h2 style="color: black;">Estado:</h2>
            </div>
            <div class="descripcion"></div>
            
        </div>
        
    </div>
        
    
</body>
</html>

Proyecto/app/templates/app/crear-empresa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/crear-perfilEmpresas.css' %}">
    <title>Crear Empresa</title>
</head>
<body>
    
    <div class="contenedor">
        <div class="header">
            <h2>Portal de Convocatorias de Practicas Facultad de ingeniería de telecomunicaciones</h2>
            <h1>CREAR EMPRESA</h1>
        </div>
        <div class="creacion">
            
            <div class="datos">
                <h1>Crear empresa</h1>
                <h2>Razón Social:</h2>
                
                <h2>Nombre de usuario:</h2>
                
                <h2>Contraseña:</h2>
                
                <h2>Ciudad:</h2>
                
                <h2>Nombre de Contacto:</h2>
                
                <h2>Correo Electrónico:</h2>
                
            </div>
            <div class="entrada">
                <form action="{% url 'app:post_crearEmpresa' %}" method="POST">
                {% csrf_token %}
                    <input type="text" name="razonsocial" id="">
                    <br>
                    <input type="text" name="usuario" id="">
                    <br>
                    <input type="password" name="contraseña" id="">
                    <br>
                    <input type="text" name="ciudad" id=""> 
                    <br>
                    <input type="text" name="contacto" id="">
                    <br>
                    <input type="text" name="correo" id="">

                    <button type="submit">CREAR</button>
                </form>
            </div>
            
        </div>
        <div class="contenedorbarra1">
            <!-- contenedor barra -->
        </div>
        <div class="contenedorbarra2">
            <!-- contenedor barra -->
        </div>
    </div>
</body>
</html>

Proyecto/app/templates/app/crear-estudiante.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/crear-perfilEstudiante.css' %}">
    <title>Crear Estudiante</title>
</head>
<body>
    
    <div class="contenedor">
        <div class="header">    
            <a  class="usuario" href="Coordinador.html"><h1>Coordinador</h1></a>
            <a  href="{% url 'app:PaginaInicio' %}">Cerrar Sesión</a>  
        </div>
        <div class="creacion">
            
            <div class="datos">
                <h1>Crear Estudiante</h1>
                <h2>Usuario:</h2>
                <h2>Contraseña:</h2>
                <h2>Nombres:</h2>
                <h2>Apellidos:</h2>
                <h2>Correo Electrónico:</h2>
                
            </div>
            <div class="entrada">
                <form action="{% url 'app:post_crearEstudiante' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="usuario" id="">
                    <br>
                    <input type="password" name="contraseña" id="">
                    <br>
                    <input type="text" name="nombres" id="">
                    <br>
                    <input type="text" name="apellidos" id="">
                    <br>
                    <input type="text" name="correo" id="">
                    <button type="submit">CREAR</button>
                </form>
            </div>
            
        </div>
        <div class="contenedorbarra1">
            <!-- contenedor barra -->
        </div>
        <div class="contenedorbarra2">
            <!-- contenedor barra -->
        </div>
    </div>
</body>
</html>

Proyecto/app/templates/app/index-PaginaInicio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/css/estilo-Inicio.css' %}">
    <title>Acceder</title>
</head>
<body>
    
    <div class="Principal">
        <div class="contenedor">
            <div class="header">
                <h2>Portal de Convocatorias de Practicas</h2>
                <h1>Facultad de Ingeniería de Telecomunicaciones</h1>
            </div>
            <div class="contenedor1">
                <!-- contenedor 1 -->
            </div>
            <div class="contenedorbarra1">
                <!-- contenedor barra -->
            </div>
            <div class="contenedorbarra2">
                <!-- contenedor barra -->
            </div>
        </div>
        <div class="contenedorIngresar">
            <!-- contenedorIngresar -->
            <form action="{% url 'app:post_login' %}" method="POST">
                {% csrf_token %}
                <h4 class="usur">Usuario:</h4>
                    
                <input class="usuario" type="text" name="usuario">
                <br>
                <h4 class="contra">Contraseña:</h4>
                <input class="contraseña" type="password" name="clave" id="">
                
                <button class="IniS" type="submit">Iniciar Sesión</button>
                <!-- <a href=""></a> -->
            </form>
            <a href="{% url 'app:Empresa' %}">Empresa</a>
            <a href="{% url 'app:Estudiante' %}">Estudiante</a>
            <a href="{% url 'app:Coordinador' %}">Coordinador</a>
            <br>
            <a href="{% url 'app:crearEmpresa' %}"><button class="CRE">Crear Empresa</button></a>
            <div class="datos">
                
            </div>
        </div>
    </div>  
</body>
</html>