Clase/BlockBuster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

Clase/app/urls.py
	
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    path('', views.index, name='index'), 
    path('peliculas/', views.peliculas,name='peliculas'),
    path('pelicula/<int:id>/', views.pelicula, name='pelicula'),
    path('pelicula/crear', views.form_crear_pelicula, name='form_crear_pelicula'),
    path('pelicula/crear_post', views.post_crear_pelicula, name='post_crear_pelicula'),

    path('categorias/', views.categorias,name='categorias'),
    path('categorias/crear', views.form_crear_categoria, name='form_crear_categoria'),
    path('categorias/crear_post', views.post_crear_categoria, name='post_crear_categoria'),
    
    path('acercade/', views.acercade,name='acercade'),

]

Clase/app/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

    class Meta():
        app_label:'app'

class Pelicula(models.Model):
    titulo= models.CharField(max_length=200)
    anio= models.IntegerField(null=True)
    sinopsis = models.TextField()
    actores= models.TextField(null=True)
    categoria = models.ForeignKey(
        Categoria,
        related_name='peliculas',
        on_delete= models.PROTECT
    )

    def __str__(self):
        return self.titulo
    class Meta:
        app_label: 'app'

Clase/app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Categoria, Pelicula
 
#Lista de peliculas
# lista=['Avatar','Titanic', 'Constantine', 'Star Wars']

# lista= [
#     {'id':0,'nombre': 'Pulp Fiction', 'year':1998},
#     {'id':1,'nombre': 'The Hateful Eight', 'year':2015},
#     {'id':2,'nombre': 'Django Unchained', 'year':2013},
#     {'id':3,'nombre': 'Kill Bill Vol.1', 'year':2004},
# ]

def index(request):
    return render(request,'app/index.html')

def acercade(request):
    return render(request,'app/acercade.html')

def peliculas(request):
    #obtiene las peliculas
    lista= Pelicula.objects.all().order_by('anio')
    contexto = {
        # 'lista_peliculas': lista,
        # 'year': 2021,
        # 'tienda': 'Blockbuster'
        'peliculas': lista

    }
    return render(request,'app/peliculas.html',contexto)

def pelicula(request, id):

#     titulo=''
#     if id ==1:
#         titulo='Avatar'
#     elif id==2:
#         titulo='Titanic'
#     elif id==3:
#         titulo='Constantine'
#     else:
#         titulo='Desconocido'
#     #Definición del contexto
#     contexto={
#         'titulo':titulo
#    }

    # #Definición del contexto
    # contexto ={}
    
    # #Verifica que el id esté dentro de la lista
    # if id < len(lista):
    #     contexto['pelicula']=lista[id]
    
    ##Ahora con models
    obj_pelicula= Pelicula.objects.get(id=id)
    contexto= {
        'pelicula': obj_pelicula
    }
    return render(request,'app/pelicula.html',contexto)

def categorias(request):
    #Obtiene todas las caegorias
    lista = Categoria.objects.all()
    #Crea el contexto
    contexto = {
        'categorias': lista
    }
    # Invoca el template enviando el contexto 
    return render(request,'app/categoria.html', contexto)

def form_crear_categoria(request):
        
    return render(request,'app/formCrearCategoria.html')

def post_crear_categoria(request):
    #Obtiene el nombre de la categoria
    nombre= request.POST['nombre']
    #Crea el Objeto
    cat=Categoria(nombre=nombre)
    #Guarda el objeto en la bd
    cat.save()
    #Redirecciona a la página categorias
    return redirect('app:categorias')

def form_crear_pelicula(request):
    #obtiene las categorias
    lista_categorias=Categoria.objects.all().order_by('nombre')
    #Crea el conexto
    contexto={
        'categorias': lista_categorias
    }
    #muestra el template con e contexto
    return render(request, 'app/formCrearPelicula.html',contexto)

def post_crear_pelicula(request):
    #Obtiene los datos del formulario
    titulo =request.POST['titulo']
    anio=request.POST['anio']
    sinopsis=request.POST['sinopsis']
    actores=request.POST['actores']
    id_categoria=int(request.POST['categoria'])

    #obtiene la categoria
    categoria=Categoria.objects.get(pk=id_categoria)

    #Crea el objeto Pelicula
    nueva_pelicula= Pelicula()
    nueva_pelicula.titulo=titulo
    nueva_pelicula.anio=anio
    nueva_pelicula.sinopsis=sinopsis
    nueva_pelicula.actores=actores
    nueva_pelicula.categoria=categoria

    #Guarda el objeto en la base de datos
    nueva_pelicula.save()
    
    #Redirecciona a la página de películas
    return redirect('app:peliculas')



    

Clase/app/templates/app/acercade.html
{% extends 'app/layout.html' %}

{% block contenido %}
    <h1>Una página hecha en Colombia</h1>
    <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facilis amet, numquam mollitia quasi modi delectus sapiente. Tempora ratione, dolor eos quasi cumque obcaecati explicabo quo, itaque cupiditate voluptate velit a.
    </p>
    <br>
{% endblock %}

Clase/app/templates/app/categoria.html
{% extends 'app/layout.html' %}

{% block titulo %} 
    
{% endblock %}

{% block contenido %}
    <h1>Categorias</h1>
    <a href="{% url 'app:form_crear_categoria' %}">Crear Categoria</a>
    <ul>
        {% for c in categorias %}
        
            <li>{{ c.nombre }}</li>
        {% endfor %}
    </ul>
{% endblock %}

Clase/app/templates/app/formCrearCategoria.html
{% extends 'app/layout.html' %}

{% block titulo %}
Crear categoría
{% endblock %}

{% block contenido %}

<form action="{% url 'app:post_crear_categoria' %}" method="POST"> 
    {% csrf_token %}
    <label for="nombre">Nombre de Categoria</label>
    <input type="text" name="nombre">
    <button type="submit">Crear</button>

</form>

{% endblock %}

Clase/app/templates/app/formCrearPelicula.html
{% extends 'app/layout.html' %}

{% block titulo %}
Crear pelicula
{% endblock %}

{% block contenido %}
<form action="{% url 'app:post_crear_pelicula'%}" method="POST">
    {%csrf_token%}
    <label for="titulo">Titulo</label>
    <input type="text" name="titulo">
    <br>
    <label for="anio">Año</label>
    <input type="number" name="anio">
    <br>
    <label for="sinopsis">Sinopsis</label>
    <textarea name="sinopsis" cols="30" rows="10"></textarea>
    <br>
    <label for="actores">Actores</label>
    <input type="text" name="actores">
    <br>
    <label for="categoria">Categoria</label>
    <select name="categoria" >
        {% for c in categorias %}
            <option value="{{c.id}}">{{c.nombre}}</option>
        {% endfor %}
    </select>
    <br>
    <button type="submit">Crear</button>

</form>
{% endblock %}

Clase/app/templates/app/index.html
{% extends 'app/layout.html' %}


{% block contenido %}
    <h1>Página de Inicio</h1>
{% endblock %}

Clase/app/templates/app/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BlockBuster</title>
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
</head>
<body>

    <div class="container">
        <div class="header">
            
            <h1><img src="{% static 'app/img/BB.png' %}" alt="BB" width="6%">BlockBuster - <small>{% block titulo %} El mejor sitio {% endblock %}</small></h1>
        </div>
        <div class="navegacion">
            <a href="{%url 'app:index'%}">Inicio</a>
            <br>
            <a href="{%url 'app:peliculas'%}">Peliculas</a>
            <br>
            <a href="{%url 'app:categorias'%}">Categorias</a>
            <br>
            <a href="{%url 'app:acercade'%}">Acercade</a>
            
        </div>
        <div class="contenido">
            {% block contenido %}
            {% endblock %}
        </div>
        <div class="footer">
            <span>Derechos Reservados - BlockBuster copy</span>
        </div>
    </div>


</body>
</html>

Clase/app/templates/app/pelicula.html
    {% extends 'app/layout.html' %}


    {% block contenido %}
    {% if pelicula %}
    <h1>{{pelicula.titulo}}</h1>
    <h3>Año</h3>
    <h3>{{pelicula.anio}}</h3>
    <h3>Sinopsis</h3>
    <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odit veritatis aperiam ullam sit incidunt accusamus, ad iste itaque delectus? Alias aliquam optio, ullam maiores illum rem consectetur excepturi esse aut.
    </p>
        {% if pelicula.actores %}
        <h3>Actores</h3>
        <p>{{ pelicula.actores }}</p>
        {% endif %}
    {% else %}
    <h1 style="color:red">La pelicula solicitada no existe!</h1>
    {% endif %}
    {% endblock %}
    
   

Clase/app/templates/app/peliculas.html
{% extends 'app/layout.html' %}

{% block titulo %} 
    Peliculas
{% endblock %}

{% block contenido %}

<a href="{% url 'app:form_crear_pelicula' %}">Crear pelicula</a>
<table border="1" width="100%">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Año</th>
        </tr>
    </thead>
    <tbody>
    {% for p in peliculas %}
        <tr>
            <td>{{ p.titulo }}</td>
            <td>{{ p.anio }}</td>
            <td>
                <a href="{% url 'app:pelicula' p.id %}">Ver</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Peliculas</title>
</head>
<body>
    <h1>Peliculas</h1>
    <p>lorem ipsum</p>
     <ul>
        {% for p in lista_peliculas %}
            <li>{{p}}</li>
        {%endfor%}
    </ul> 
    
    {% comment %}
        <ul>
        <li>Avatar</li>
        <li>Titanic</li>
        <li>Constantine</li>
        </ul>
    {% endcomment %}
    <hr>
    <span>Derechos reservados {{year}} - {{tienda}}</span>
</body>
</html> -->